### ISSUE TITLE
Additional builds

### ISSUE THREAD

**Issue by NikoofDeath** [ikonomov/devilutionXLE#5]
Currently, you're only releasing automated builds for the platforms that devilutionx builds using github actions - the ones built with circleci and appveyor (e.g. switch, vita, xbox one) are not built. While it is not too much trouble to build these personally on occasion, having automated builds would be much more convenient for consistent bleeding edge updates. At the very least, if not setting up automated builds, at least having release builds for these platforms would make sense.

**Comment by ikonomov** [comment]
> Currently, you're only releasing automated builds for the platforms that devilutionx builds using github actions - the ones built with circleci and appveyor (e.g. switch, vita, xbox one) are not built. While it is not too much trouble to build these personally on occasion, having automated builds would be much more convenient for consistent bleeding edge updates. At the very least, if not setting up automated builds, at least having release builds for these platforms would make sense.

To be honest I didn't think there would be enough interest for people to play my mod in order to have those builds.  haha I did consider setting it up...

**Comment by ikonomov** [comment]
Looks like DevX now has github workflows for xbox and xbox.  I think I'll leave it here without circleci and appveyor for now.
